// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_d5exHEEr2tKyn8x1ErQaQjh9dKGq30',
    appId: '1:290403969523:web:8201a70e53410fad118a86',
    messagingSenderId: '290403969523',
    projectId: 'fir-flutter-codelab-6d277',
    authDomain: 'fir-flutter-codelab-6d277.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6d277.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuj0e0I-_pE6wtKjU_ddcOWy2oEXeZq4',
    appId: '1:290403969523:android:217710455c2111d3118a86',
    messagingSenderId: '290403969523',
    projectId: 'fir-flutter-codelab-6d277',
    storageBucket: 'fir-flutter-codelab-6d277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnxN4Q5HArSVuHc-UFqEgvBQjbfymCl0',
    appId: '1:290403969523:ios:1285e028b789a697118a86',
    messagingSenderId: '290403969523',
    projectId: 'fir-flutter-codelab-6d277',
    storageBucket: 'fir-flutter-codelab-6d277.appspot.com',
    iosClientId: '290403969523-qphlv54l9srf28qhfsao1v500pvt08j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterCodelab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYnxN4Q5HArSVuHc-UFqEgvBQjbfymCl0',
    appId: '1:290403969523:ios:1285e028b789a697118a86',
    messagingSenderId: '290403969523',
    projectId: 'fir-flutter-codelab-6d277',
    storageBucket: 'fir-flutter-codelab-6d277.appspot.com',
    iosClientId: '290403969523-qphlv54l9srf28qhfsao1v500pvt08j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterCodelab',
  );
}
